services:
  mailpit:
    image: axllent/mailpit:v1.27.7
    environment:
      MP_DATABASE: /data/mailpit.db
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"
    volumes:
      - mailpit-data:/data

volumes:
  mailpit-data:
